steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - function_cicd
      - --region=us-central1
      - --source=.
      - --trigger-http
      - --runtime=python311
      - --allow-unauthenticated
      - --gen2

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1200s